web:
  build: .
  command: python -u app.py
  ports:
    - "7800:7800"
  volumes:
    - .:/todo
  links:
    - db
db:
  image: 'mongo:latest'
  command: mongod --port 27017
  ports:
      - '27017:27017'
